### ISSUE TITLE
using foo_discord_rich instead of foo_drpc

### ISSUE THREAD

**Issue by worf1337** [rafetefe/foobar_wine_drpc#1]
hey,

can i ask how you made this? i'm trying to use this with foo_discord_rich instead of foo_drpc and it isn't working. even tried extracting the dll from the fb2k-component file and putting it in components but still no luck

thanks in advance

**Comment by rafetefe** [comment]
After your issue I tried to retry this trick and got my wine foobar running with discord rich presence.

I couldn't got "foo_discord_rich" running. Maybe someone else can do it.

But I did got managed to get myself a rich presence by using the current DLLs in the repo and placing them into the components folder of 32bit portable foobar2000 installation.

I wasn't been using this setup for a while, feel free to reply or ask for anything else.

And for your question, I was just trying to make it work and managed to get it running with these 2 dlls coincidentally. Probably they somehow complete each other.

**Comment by worf1337** [comment]
interesting, thank you for trying 🫡
